### ISSUE TITLE
Messages appear in a darker color than usual.

### ISSUE THREAD

**Issue by Mihai2893** [vednoc/dark-whatsapp#167] opened 2020-06-18 07:59 UTC
After a while of using the font color changes only for current messages from the light one (fg-3: #d1d1d1 --fg-3-rgb: 209,209,209 I think) to some darker one. The problem does not affect the text in a reply box or the contacts on the left. The hex code for the new gray color is #303030 (19% white. d1d1d1 is 82%white, which makes me thing it is some sort of reversed color scheme) but I don't know if it's just a darker shade of the normal because of some shadow setting or something else.
Browser Chrome, up to date 18.06.2020
I hope the screenshot shows enough to show the problem. Thank you

Edit: Removed unnecessary white background.

![image](https://user-images.githubusercontent.com/18245694/85009735-36f11480-b15f-11ea-88d2-fcb624daf93c.png)

**Comment by vednoc** [comment] 2020-06-18 10:28
Can you tell us what version of Dark-WhatsApp and WhatsApp Web you're on? I can't reproduce this on my end.

**Comment by DanBeast1337** [comment] 2020-06-18 11:24
Same here, DWA 2.13.0 and WAW Version 2.2025.6. 
Reinstalled the style, same issue. Screenshot is with a clean style-install. 

![image](https://user-images.githubusercontent.com/9980963/85014656-f39aa400-b166-11ea-9b63-9352f2bf0219.png)

**Comment by Mihai2893** [comment] 2020-06-18 11:53
The WAW is also 2.2025.6 and the Dark-WhatsApp I am not very sure since i don't know where to find it but I assume it's the latest since I downloaded it again from Stylish today. Regards

**Comment by vednoc** [comment] 2020-06-18 12:17
> WAW version `2.2025.6`

I knew this was most likely it, and the update just landed on my end. There are more things that are broken, and an update will be out shortly. Try refreshing the page a few times until it loads the previous `2.2023.2` version as a temporary hotfix.


> Dark-WhatsApp I am not very sure since i don't know where to find it 

You can see it by clicking on the gear icon from Stylus popup, or from the Stylus manage page, or on the intro page below the logo.
![image](https://user-images.githubusercontent.com/18245694/85018513-90604000-b16d-11ea-9521-107baff510bb.png)

**Comment by vednoc** [comment] 2020-06-18 12:22
> [...] I downloaded it again from Stylish today.

I didn't notice at first that you're using Stylish, the first two options to check DWA version will probably not work there. I suggest switching over to Stylus if you'd like to get auto-updates as well as to customize option in the configuration menu. 😄

**Closed** 2020-06-18 13:27 UTC
Labels: bug

**Comment by vednoc** [comment] 2020-06-18 13:31
Update is now out! 🎉

**Comment by Mihai2893** [comment] 2020-06-18 18:50
Worked perfectly. Thank you. I was using Stylish and the customization was not a big problem since I could figure out how to customize from the code directly but switched to Stylus now. 
Have a great day!

**Comment by vednoc** [comment] 2020-06-19 19:18
> I could figure out how to customize from the code directly

For the most part, that's no longer necessary anymore thanks to [UserCSS configuration menu][0], and the best part is that changes also persist after updating to new versions. 😃 


[0]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration
