### ISSUE TITLE
Chat background image inverted colors option resets on its own every couple of days

### ISSUE THREAD

**Issue by Wroargh** [vednoc/dark-whatsapp#169] opened 2020-06-26 10:11 UTC
Been doing it since the start iv'e been using this, haven't figured out what exactly causes it, but i'm on latest Vivaldi browser, turning other extensions off / on don't seem to do anything about it.

**Comment by vednoc** [comment] 2020-06-26 10:48
What are the values that you use for chat background options? I'll have to reproduce this on my end in order to fix it, but it's just bizarre to me that it does that; I've never experienced anything similar. 🤔

**Comment by Wroargh** [comment] 2020-06-26 10:56
Iv'e set it to 0 value, but once it resets, it's at 0.6 value.

**Comment by vednoc** [comment] 2020-06-26 11:17
Alright, cool! I made a similar setup on my end and will try a few things to reproduce this issue, although I can't guarantee it will be successful.

**Comment by Wroargh** [comment] 2020-06-26 11:18
All good! We will see.

**Comment by vednoc** [comment] 2020-06-26 18:58
No luck thus far. Let me know if/when this issue occurs again.

**Comment by Wroargh** [comment] 2020-06-26 19:08
Will do, thanks.

**Comment by vednoc** [comment] 2020-07-01 09:12
I sort of managed to reproduce the issue. There will be one more reset (it's inevitable, had to change the key for this option), and from there on out everything will work properly. Also there is no need to reinstall the userstyle.

**Comment by Wroargh** [comment] 2020-07-02 07:58
Hmm i don't know, the issue happened again this morning.

**Comment by vednoc** [comment] 2020-07-02 10:41
Yep, that's because you got the `v2.16.0` update. Feel free to reopen this issue if it happens after today's update. It really shouldn't since `chat_bg_i` key has been replaced with `chat_bg_iv`, but we'll see; check the linked commit to see what I changed. 😄

**Comment by Wroargh** [comment] 2020-07-02 11:06
Okay, gotcha.

**Comment by Wroargh** [comment] 2020-07-04 05:45
Umm, it did reset again this morning. That's odd.

**Comment by vednoc** [comment] 2020-07-04 20:30
Seems like something is wrong with Stylus. Changing the key fixed it on my second browser that was having this issue.

Try the following:
1. Delete Dark-WhatsApp
2. Install [version 2.16.0][0]
3. Set your chat background options
4. Upgrade to the [newest version][1]

If this doesn't help either (the invert will reset to default value), I'll improve chat background options in the `v2.17.0` release even though that was planned for `v3.0.0`. The invert will be at 0 by default, and chat background image will be the one from native dark mode.

[0]: https://github.com/vednoc/dark-whatsapp/raw/2.16.0/wa.user.styl
[1]: https://raw.githubusercontent.com/vednoc/dark-whatsapp/master/wa.user.styl

**Comment by Wroargh** [comment] 2020-07-05 03:43
Right, ill give this a go.

**Comment by Wroargh** [comment] 2020-07-11 11:30
No issues what so ever for 6 days, thinking that might have resolved the issue.

**Comment by vednoc** [comment] 2020-07-11 19:02
That's promising! The final test will be if it doesn't break after a new update. Should everything go well, feel free to close this issue.

**Closed** 2020-07-14 17:10 UTC
Labels: bug
